---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-workload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiops-agentcore-workload
  namespace: demo-workload
  labels:
    app: aiops-agentcore-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiops-agentcore-workload
  template:
    metadata:
      labels:
        app: aiops-agentcore-workload
    spec:
      containers:
        - name: app
          image: 099139718958.dkr.ecr.ca-central-1.amazonaws.com/aiops-agentcore-workload
          ports:
            - containerPort: 8000
          env:
            - name: LEAK_ENABLED # enable leak
              value: "false" # debug by "false"
            - name: LEAK_START_SECONDS # leak start time
              value: "120" # 2min
            - name: LEAK_MB_PER_TICK
              value: "4"
            - name: LEAK_INTERVAL_SECONDS
              value: "1"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi" # memory limit to breah
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            # defer health probe
            initialDelaySeconds: 300
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: aiops-agentcore-workload
  namespace: demo-workload
spec:
  type: ClusterIP
  selector:
    app: aiops-agentcore-workload
  ports:
    - port: 8000
      targetPort: 8000
